
name: BUILD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - name: Install dependencies
        working-directory: ./website
        run: npm i

      - name: Build website site
        working-directory: ./website
        run: npm run website:build

      - uses: actions/upload-artifact@v2
        with:
          name: website
          path: dist/

      - uses: w9jds/firebase-action@master
        with:
          args: deploy --project chattycat-site --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
